#!/bin/bash

BLUE='\033[0;34m'
GREEN='\033[0;32m'
RED='\033[0;31m'

PWD=$(pwd)

statusOutput=$(git status -s)

if [ "$statusOutput" = "" ]; then
	echo "nothing to do"
	exit 0
fi
echo -e "${GREEN}"
echo -e " ██████  ██ ████████      █████  ██████  ██████  "
echo -e "██       ██    ██        ██   ██ ██   ██ ██   ██ "
echo -e "██   ███ ██    ██        ███████ ██   ██ ██   ██ "
echo -e "██    ██ ██    ██        ██   ██ ██   ██ ██   ██ "
echo -e " ██████  ██    ██        ██   ██ ██████  ██████  "
echo -e "\n\033[0m"

echo -e "${BLUE}What do you need to add? Don't put anything for all and to end press 2 times in a row"
echo -e "\033[0m"
echo -e "${BLUE}The status of your actual reposite :"
echo -e "\033[0m"

git status -s

read -r userInput

if [ "$userInput" = "" ]; then
    git add .
else

    if [ -f "$PWD/$userInput" ]; then
        git add "$userInput"
    else
        echo -e "$userInput is not a file or does not exist."
    fi

    while [ "$userInput" != "" ]; do
        read -r userInput
        if [ -f "$userInput" ]; then
	    git add "$userInput"
	else
	    echo -e "$userInput is not a file or does not exist."
	fi
    done
fi

echo -e "${GREEN}"
echo -e " ██████  ██ ████████      ██████  ██████  ███    ███ ███    ███ ██ ████████ "
echo -e "██       ██    ██        ██      ██    ██ ████  ████ ████  ████ ██    ██    "
echo -e "██   ███ ██    ██        ██      ██    ██ ██ ████ ██ ██ ████ ██ ██    ██    "
echo -e "██    ██ ██    ██        ██      ██    ██ ██  ██  ██ ██  ██  ██ ██    ██    "
echo -e " ██████  ██    ██         ██████  ██████  ██      ██ ██      ██ ██    ██    "
echo -e "\n\033[0m"

echo -e "${BLUE}Choose your tag for the commit! ex: ADD, FIX, DELETE, UPDATE..."
echo -e "\033[0m"

read -r userTag

uppercaseTag="${userTag^^}"

echo -e "${BLUE}Put the content of your commit!"
echo -e "\033[0m"

read -r userComment

echo -e "${RED}Commit message : [$uppercaseTag] $userComment"
echo -e "\033[0m"
git commit -m "[$uppercaseTag] $userComment" > /dev/null

echo -e "${GREEN}"
echo -e " ██████  ██ ████████     ██████  ██    ██ ███████ ██   ██ "
echo -e "██       ██    ██        ██   ██ ██    ██ ██      ██   ██ "
echo -e "██   ███ ██    ██        ██████  ██    ██ ███████ ███████ "
echo -e "██    ██ ██    ██        ██      ██    ██      ██ ██   ██ "
echo -e " ██████  ██    ██        ██       ██████  ███████ ██   ██ "
echo -e "\n\033[0m"

git push
