#!/bin/bash

BLINK='\033[5m'
GREEN='\033[0;32m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

WAIT_DIR="$HOME/Epitech/project/save_project"
SAVE_DIR="$HOME/Epitech/project/save_project/Projet_Tek1"

if [ ! -d "$WAIT_DIR" ]; then
  echo -e "${BOLD}${RED}ERROR: $WAIT_DIR directory does not exist.${NC}"
  exit 84
fi

if [ ! -d "$SAVE_DIR" ]; then
  echo -e "${BOLD}${RED}ERROR: $SAVE_DIR directory does not exist.${NC}"
  exit 84
fi

if [ ! -d "$1" ]; then
  echo -e "${BOLD}${RED}ERROR: File $1 does not exist.${NC}"
  exit 84
fi

cp "$1" "$WAIT_DIR" -rf

if [ ! $? ]; then
  echo -e "${BOLD}${RED}ERROR: Failed to copy directory.${NC}"
  exit 84
fi

rm "$WAIT_DIR/$1/.git" -rf >/dev/null

mv "$WAIT_DIR/$1" "$SAVE_DIR"

if [ ! $? ]; then
  echo -e "${BOLD}${RED}ERROR: Failed to move directory.${NC}"
  exit 84
fi

echo -e "${GREEN}${BOLD}${BLINK}Script executed successfully.${NC}"
